using Newtonsoft.Json;

namespace MomirDinA4.ScryfallApiObjects;

[method: JsonConstructor]
public record Card(
    [property: JsonProperty("object")] string Object,
    [property: JsonProperty("id")] string Id,
    [property: JsonProperty("oracle_id")] string OracleId,
    [property: JsonProperty("multiverse_ids")] IReadOnlyList<object> MultiverseIds,
    [property: JsonProperty("tcgplayer_id")] int? TcgplayerId,
    [property: JsonProperty("name")] string Name,
    [property: JsonProperty("lang")] string Lang,
    [property: JsonProperty("released_at")] string ReleasedAt,
    [property: JsonProperty("uri")] string Uri,
    [property: JsonProperty("scryfall_uri")] string ScryfallUri,
    [property: JsonProperty("layout")] string Layout,
    [property: JsonProperty("highres_image")] bool? HighresImage,
    [property: JsonProperty("image_status")] string ImageStatus,
    [property: JsonProperty("image_uris")] ImageUris ImageUris,
    [property: JsonProperty("mana_cost")] string ManaCost,
    [property: JsonProperty("cmc")] double? Cmc,
    [property: JsonProperty("type_line")] string TypeLine,
    [property: JsonProperty("oracle_text")] string OracleText,
    [property: JsonProperty("power")] string Power,
    [property: JsonProperty("toughness")] string Toughness,
    [property: JsonProperty("colors")] IReadOnlyList<string> Colors,
    [property: JsonProperty("color_identity")] IReadOnlyList<string> ColorIdentity,
    [property: JsonProperty("color_indicator")] IReadOnlyList<string> ColorIndicator,
    [property: JsonProperty("keywords")] IReadOnlyList<string> Keywords,
    [property: JsonProperty("games")] IReadOnlyList<string> Games,
    [property: JsonProperty("reserved")] bool? Reserved,
    [property: JsonProperty("game_changer")] bool? GameChanger,
    [property: JsonProperty("foil")] bool? Foil,
    [property: JsonProperty("nonfoil")] bool? Nonfoil,
    [property: JsonProperty("finishes")] IReadOnlyList<string> Finishes,
    [property: JsonProperty("oversized")] bool? Oversized,
    [property: JsonProperty("promo")] bool? Promo,
    [property: JsonProperty("reprint")] bool? Reprint,
    [property: JsonProperty("variation")] bool? Variation,
    [property: JsonProperty("set_id")] string SetId,
    [property: JsonProperty("set")] string Set,
    [property: JsonProperty("set_name")] string SetName,
    [property: JsonProperty("set_type")] string SetType,
    [property: JsonProperty("set_uri")] string SetUri,
    [property: JsonProperty("set_search_uri")] string SetSearchUri,
    [property: JsonProperty("scryfall_set_uri")] string ScryfallSetUri,
    [property: JsonProperty("rulings_uri")] string RulingsUri,
    [property: JsonProperty("prints_search_uri")] string PrintsSearchUri,
    [property: JsonProperty("collector_number")] string CollectorNumber,
    [property: JsonProperty("digital")] bool? Digital,
    [property: JsonProperty("rarity")] string Rarity,
    [property: JsonProperty("card_back_id")] string CardBackId,
    [property: JsonProperty("artist")] string Artist,
    [property: JsonProperty("border_color")] string BorderColor,
    [property: JsonProperty("frame")] string Frame,
    [property: JsonProperty("full_art")] bool? FullArt,
    [property: JsonProperty("textless")] bool? Textless,
    [property: JsonProperty("booster")] bool? Booster,
    [property: JsonProperty("story_spotlight")] bool? StorySpotlight,
    [property: JsonProperty("promo_types")] IReadOnlyList<string> PromoTypes,
    [property: JsonProperty("mtgo_id")] int MtgoId,
    [property: JsonProperty("card_faces")] IReadOnlyList<CardFace> CardFaces,
    [property: JsonProperty("flavor_name")] string FlavorName
    )
{
}